version: 1
services:
  - name: frontend
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    env:
      - key: REACT_APP_API_URL
        value: https://your-backend-api-url
    envFiles:
      - .env.production
