version: 1
services:
  - name: backend
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    env:
      - key: MONGO_STRING
        value: mongodb+srv://123:123@project-3.xsibmes.mongodb.net/Sticky_notes?retryWrites=true&w=majority
    envFiles:
      - .env.production
